### ISSUE TITLE
There's a problem with terminal scrolling

### ISSUE THREAD

**Issue by FrazzoJustACoder** [Bone-Project/BoneOS#103]
![virtualbox_others_17_12_2016_22_20_38](https://cloud.githubusercontent.com/assets/20447641/21289848/a4efb8c2-c4a7-11e6-82f0-36cc21ef2c6b.png)

**Comment by amanuel2** [comment]
Wont work in VMWare either Need support for APCI Shutdown. (Later releases)

**Comment by amanuel2** [comment]
Wasnt a terminal issue.  need to have a space between newline(/n)  and tab(/t)

**Comment by amanuel2** [comment]
Solved.
