### ISSUE TITLE
TAB

### ISSUE THREAD

**Issue by amanuel2** [Bone-Project/BoneOS#109]

**Comment by amanuel2** [comment]
Assigned to @Fortunate-MAN

**Comment by double-fault** [comment]
Closing this now. Fixed

**Comment by amanuel2** [comment]
Actually have some finishing touches to do

**Comment by amanuel2** [comment]
https://github.com/Bone-Project/BoneOS/commit/e566def85e86fd547feebe2e4d7f70e430a478d9 .. Partial done @Fortunate-MAN

**Comment by amanuel2** [comment]
Will be worked on next release

**Comment by double-fault** [comment]
@amanuel2 I'm working on it now. If the release is going to after a few hours, I guess I can finish it.

**Comment by double-fault** [comment]
Fixed.
