### ISSUE TITLE
Space character gets ignored

### ISSUE THREAD

**Issue by srifqi** [Bone-Project/BoneOS#122]
I just tried to use BoneOS. I download freshly both BoneOS and VirtualBox VM. Then, I tried to use ```echo --help``` command. But it replied ```Invalid Command 'echo--help'```.

```
root@boneos:/ $ echo --help
Invalid Command 'echo--help'
Try 'help' for more information.
```

![screenshot](https://cloud.githubusercontent.com/assets/4017302/21558565/ac934a1e-ce6e-11e6-9b6d-daa187333d4f.png)

**Comment by double-fault** [comment]
Fixing this right now. Know what the problem is.

**Comment by double-fault** [comment]
Fixed.

**Comment by srifqi** [comment]
Seems like working, good job!

![screenshot 45](https://cloud.githubusercontent.com/assets/4017302/21567134/4bcd4eb4-cedc-11e6-84aa-862e55b688e1.png)
