### ISSUE TITLE
Real Time Clock

### ISSUE THREAD

**Issue by double-fault** [Bone-Project/BoneOS#138]
BoneOS needs a real time clock which I now know how to make. Will implement it whenever I'm free.

**Comment by amanuel2** [comment]
What? It already does

**Comment by amanuel2** [comment]
Are you trying to talk about turning on IRQ 8? http://wiki.osdev.org/RTC#IRQ_Danger .. I mean it has a low prioirty making it not as reliable as sending i/o to CMOS Registers .... CHanging the interrupt rate might be your other decision but that can interfere with the RTC capability to keep proper time.

**Comment by double-fault** [comment]
@amanuel2 Right now, you cannot change the time in the real time clock which a normal user on OS's like Ubuntu can. We need to implement that with a couple of other things.

**Comment by amanuel2** [comment]
You can change clock via terminal?

**Comment by double-fault** [comment]
@amanuel2 yes, you can. http://askubuntu.com/a/342856/493875

**Comment by amanuel2** [comment]
@Fortunate-MAN Rishav made a good point here : http://chat.stackoverflow.com/transcript/message/34945256#34945256
