### ISSUE TITLE
Error in input 

### ISSUE THREAD

**Issue by justinmarma** [Bone-Project/BoneOS#166]
Deleting written charactors only work until beginning line, not line above if input was greater than 1 line

**Comment by amanuel2** [comment]
Can you show a screenshot representing this problem?

**Comment by amanuel2** [comment]
Nope.. it works:

<img src="http://i.imgur.com/EzZIyya.png"/> . Show a screenshot or sadly this issue remains closed.

**Comment by justinmarma** [comment]
I linked a screenshot, the overflow needs to be 246 < x < 256(crashes here)
 Your input wont crash it as itś only 1 line, It should seriously be opened
if it isnt already.

**Comment by amanuel2** [comment]
Can you set up a screenshot?

**Comment by justinmarma** [comment]
@amanuel2 Yes
I'm working on screenshotting it all

**Comment by justinmarma** [comment]
@amanuel2 It is hard to screen shot the effect, Open BoneOS and on the main screen write out a sentance that forces a new line to be made, then try to delete the whole thing
Notice where the cursor is.
[Link to image](http://prntscr.com/dwxq2y)

**Comment by double-fault** [comment]
I tried what you said (or what I understood), and I could not repro this. Closing this till you can give clear steps of how to repro this. You last comment @justinmarma is pretty unclear. It _must_ be difficult to capture it, but till you give us proper steps to repro it we can't help you. Sorry.
