### ISSUE TITLE
Cursor support: more features

### ISSUE THREAD

**Issue by double-fault** [Bone-Project/BoneOS#176]
The `cursor` command works, but it does not allow enough customizations from the user. For example, the user cannot change the blinking speed and there is no I-beam cursor by default in the list of default cursors. We need to support this.

**Comment by amanuel2** [comment]
Sorry changing cursor is not possible with VGA Textmode.

**Comment by double-fault** [comment]
@amanuel2 but the `cursor` command does change the cursor to either underline or block. So all I'm saying is we should also support I-beam cursor by default.

**Comment by amanuel2** [comment]
No you can not have an I-beam cursor in VGA Textmode.
