### ISSUE TITLE
Correctly show the commands in order 

### ISSUE THREAD

**Issue by amanuel2** [Bone-Project/BoneOS#177]
Can one of you correctly make this alligned.. Code at [here](https://github.com/Bone-Project/BoneOS/blob/master/bin/help/help.c#L47)..

Screenshot : 

<img src="http://i.imgur.com/mTOcNfq.png"/>

**Comment by double-fault** [comment]
Will do this after I finish left and right arrow key support.

**Comment by srifqi** [comment]
How about like this, @amanuel2? I think, it is better with 2 columns.

![Trying to realign help.](https://cloud.githubusercontent.com/assets/4017302/22153297/580d331e-df59-11e6-82d1-e1c1a4c3d991.png)

Also, should we use 1 based index, instead of 0 based index?

**Comment by double-fault** [comment]
@srifqi that looks good. Can you make a PR with that code?

**Comment by amanuel2** [comment]
@Fortunate-MAN what is this?

<img src="http://i.imgur.com/JTPzSc4.png"/> .. @srifqi can you please update your branch and pull? Thanks

**Comment by srifqi** [comment]
Last thing, please answer my question:
> Also, should we use 1 based index, instead of 0 based index?

**Comment by amanuel2** [comment]
Base 1 index @srifqi

**Comment by srifqi** [comment]
@amanuel2 like this?

![base 1 index?](https://cloud.githubusercontent.com/assets/4017302/22170235/16cda8f2-dfae-11e6-98ba-7518758f9aa1.png)

**Comment by amanuel2** [comment]
Yes!
