### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by double-fault** [Bone-Project/BoneOS#179]
I'm going to start writing all the documentation again, as the current docs on GitBook is pretty horrible. I'll be putting the docs in the `Documentation/` directory. Once I finish writing the docs, @onlineth  will put them on the website.

I consider this pretty high priority as if someone comes to this repo, and wants to run it and try different commands, the current help is pretty unclear.

If someone wants to help out, please first post a comment on this issue (note that if you are going to be writing some docs, please keep the English pretty clear and short. If you are not well versed in English, no need to contribute to this issue. Please also avoid emojis and such symbols while writing official documentation).

Some points to be noted while creating these files:
 - All files are supposed to be in Markdown `.md` format.
 - Try to keep the files as short as possible and to the point.
 - Keep the English clear.

**Comment by double-fault** [comment]
As I'm kinda busy right now, this might take some time, but I'll try to speed it up as much as possible.

**Comment by onlineth** [comment]
The documentation (unless there are any objections) will be located at https://docs.boneos.org/ and hosted by https://ReadTheDocs.org. Whoever is working on the documentation, if you could give me your RTD username's, I can add you as maintainers. Also, I need a description for the project itself, can anyone write on up?

Thanks!

**Comment by double-fault** [comment]
@onlineth could you add me to the maintainers? My username is `Ashish7`.

**Comment by double-fault** [comment]
Also, for the description for the project @onlineth , how is this sounding: 

> BoneOS is an Operating System designed to be simple and at the same time powerful. 

Is that okay, or do you want something more detailed? Also, can that be changed afterwards?

**Comment by double-fault** [comment]
@onlineth if I have understood correctly, the docs have to be in a folder called `docs` right? Lemme try that...

**Comment by onlineth** [comment]
Sorry (in a different timezone, I'm in the U.S.) `Ashish7` has been added to the maintainers and I have updated the description that you have provided. This can be changed at any time. As far as the folder goes, I'm not sure. I see that in most projects, it's called `docs` so lets us that. In any case, I will be doing some more research on this tonight.

**Comment by double-fault** [comment]
@onlineth ok thanks! I'm checking that out now.

**Comment by double-fault** [comment]
I have finished quite a bit of docs, but am right now working on the troubleshooting docs.

**Comment by double-fault** [comment]
@onlineth I get an error when I try to access `docs.boneos.org` which says something like `Maze not found`. Is this a bug or have you not configured this completely?

**Comment by onlineth** [comment]
Looking into this now

**Comment by double-fault** [comment]
ok, I'm going to go to sleep in 15 minutes, so I _might_ not reply later.

**Comment by onlineth** [comment]
ok, by the end of today, I should have docs up and running automatically

**Comment by double-fault** [comment]
great! I'm currently putting the docs in different directories so that it will be easier to navigate through them, will push before I sleep.

**Comment by double-fault** [comment]
@onlineth I have finished putting the docs in different directories. So now, the _very_ basic docs are completed, but I still need to add more. Now I'm going to go to sleep.

**Comment by double-fault** [comment]
@onlineth fyi, whenever I press "Login" on the top right corner in `docs.boneos.org`, it just redirects me to the main RTD website where I am already logged in.

**Comment by double-fault** [comment]
I guess that will be fixed once you complete the whole docs, but just posting in here so that you know. Now really off to sleep.

**Comment by ghost** [comment]
Can I translate documentation in italian? :D

**Comment by double-fault** [comment]
@xdev31 if you want to you can, but put them in a different folder (something like `ItalianDocs`).

**Comment by double-fault** [comment]
@onlineth are the docs ready?

**Comment by onlineth** [comment]
@Fortunate-MAN I'm still looking into this, I've been distracted with some other work

**Comment by double-fault** [comment]
@onlineth ok sure, np. Take your time and do it whenever you are free. I still haven't completed the docs.

**Comment by onlineth** [comment]
@Fortunate-MAN lol, this fixed it:) https://github.com/Bone-Project/BoneOS/commit/40045f4ecaa6bbcfa4337b0a0f95114d4517bee8

**Comment by double-fault** [comment]
@onlineth awesome! thanks a lot! I'm going to go afk for a few hours, and then I'll do some changes.

**Comment by double-fault** [comment]
also, is there a way to put some files in specific places in the Table of Contents in the left @onlineth ?

**Comment by onlineth** [comment]
Yes, there is, if you'd like to play around with that, make a branch to just test stuff and I can add the branch to the build process of read the docs.

**Comment by double-fault** [comment]
@onlineth no need for a new branch, I'll first just get a bit more familiar with RTD. Do you have a link to pinning files in specific places?

**Comment by double-fault** [comment]
I am going afk now. You can just drop the link here, I'll read it later. Thanks again!

**Comment by onlineth** [comment]
I'm not sure to be honest, but I do know that the documentation is built with mkdocs. I think here would be a good place to get started, http://www.mkdocs.org/user-guide/writing-your-docs/.

**Comment by onlineth** [comment]
Note that this label can be replaced with the existing documentation system,

https://img.shields.io/badge/docs-latest-brightgreen.svg?style=flat

![](https://img.shields.io/badge/docs-latest-brightgreen.svg?style=flat)

**Comment by onlineth** [comment]
Note that this badge can replace the existing documentation badge when this issue is complete

[![Documentation Status](https://readthedocs.org/projects/boneos/badge/?version=latest)](http://docs.boneos.org/en/latest/?badge=latest)

**Comment by amanuel2** [comment]
Go Edit that @onlineth

**Comment by double-fault** [comment]
@onlineth okay, looking into that link.

**Comment by double-fault** [comment]
@onlineth okay, I have create the mkdocs.yml and added quite a few things in it. It works properly!

**Comment by double-fault** [comment]
I have completed around 70% of the docs. I still have to give the final touches and write some more docs, so don't close this issue yet.

**Comment by double-fault** [comment]
The documentation is basically finished. If you see any problems in the docs, please post a new issue.

Closing this now.

**Comment by amanuel2** [comment]
@Fortunate-MAN  you forgot to add Changing RAM.. Also remember Changing RAM For now only is avilable for qemu since thats the only method we have now to boot from Makefile : https://github.com/Bone-Project/BoneOS/blob/master/Makefile#L240

**Comment by double-fault** [comment]
@amanuel2 done.

**Comment by amanuel2** [comment]
Ok cool
