### ISSUE TITLE
Remove Meta.BoneOS.org from the website

### ISSUE THREAD

**Issue by onlineth** [Bone-Project/BoneOS#184]
Meta.BoneOS.org is going down and should be moved to the issues here https://github.com/Bone-Project/BoneOS/issues.

**Comment by double-fault** [comment]
I completely agree with changing the links from the meta site to the issues, but in the future we _may_ need a forum so it is better if we don't use it right now, but we just keep it for future uses.

**TL;DR**, it is better if we keep the forum but don't use it right now.

**Comment by onlineth** [comment]
@Fortunate-MAN I agree, when the project gets much bigger (which at the rate it's going now, it won't be that long), we'll request Discourse for one of their free hosted instances or I'll find a way to host it myself. The other meta.boneos.org was simply not being used.

**Comment by double-fault** [comment]
Also, to elaborate on your issue, are you just asking to change all links or are you asking to completely remove the meta?

**Comment by onlineth** [comment]
meta.boneos.org will go away completely tomorrow. I'll add a redirect to it where meta.boneos.org will redirect to https://github.com/Bone-Project/BoneOS/issues but it still should be removed from our documentation and our website.

**Comment by double-fault** [comment]
Heh, I see your point. No need to remove it from the GitBook docs, as I'm working on new docs where I am not including the meta site.

**Comment by double-fault** [comment]
Also, later on, would you be able to create something like `docs.boneos.org`?

We are planning to host the docs on the website itself

**Comment by onlineth** [comment]
Sure, but I would like to make the website dynamic if possible, maybe use WordPress?

**Comment by onlineth** [comment]
I can host that no problem, maybe use that at least for the documentation?

**Comment by double-fault** [comment]
I am okay with anything, just I would like if Markdown was supported and the UI would be simple and something like Read The Docs where we can navigate through pages easily.

**Comment by double-fault** [comment]
Without Markdown also, we can make the docs, but it would make it easier for someone to edit the docs if Markdown was supported.

**Comment by onlineth** [comment]
Sure, (completely forgot about that)

**Comment by double-fault** [comment]
Ok, I'll ping you over here once I complete a bunch of docs and we are ready to publish them. Thanks!

**Comment by double-fault** [comment]
I am now going afk for a few hours, will be back in the evening.

**Comment by double-fault** [comment]
Also, I'll start changing links whenever I get time.

**Comment by onlineth** [comment]
When you get back on, give me your readthedocs username, our documentation will be located at docs.boneos.org

**Comment by onlineth** [comment]
Continuing the documentation conversation here: https://github.com/Bone-Project/BoneOS/issues/179

**Comment by ghost** [comment]
Dear @onlineth,
I saw the situation, we can host a forum in a free hosting... I think we don't need a hosting with unlimited GB and unlimited mails...

**Comment by onlineth** [comment]
@xdev31 Hosting was never the issue, I have my own vps that I could host for free. The forum was not being used and I believe along with @Fortunate-MAN that *for now* GitHub issues is a great resource for a temporary forum. In the future, I and @amanuel12 would like to use Discourse which can import GitHub issues.
