### ISSUE TITLE
Backspace Key Bug

### ISSUE THREAD

**Issue by srifqi** [Bone-Project/BoneOS#190]
BoneOS Version : 0.0.2 (`make` from 31ac2b84f467f7c2a904160007e3748fa70f4745)

Describe Problem :

When you enter some text, then press <kbd>Left</kbd> and then press <kbd>Backspace</kbd> it deletes second character from end but it displays as if the last character is deleted.

[Video](https://youtu.be/Vz0QXMuv89M)

**Comment by double-fault** [comment]
heh, looks like no one noticed this bug. Fixing this right now..

**Comment by double-fault** [comment]
extremely weird bug..

**Comment by double-fault** [comment]
Fixed with an _extremely_ small change :)
