### ISSUE TITLE
Make autocomplete for TAB an option

### ISSUE THREAD

**Issue by double-fault** [Bone-Project/BoneOS#192]
Right now, if you type `po` and press the TAB key, it automatically executes the `poweroff` command which I find useful in many cases. But, some people don't (including me in cases, for example I want to run `poweroff --help` so I have to type the whole thing with the current TAB), so I plan to provide the functionality to switch between the two.

I know how to do this, will do it afterwards.

**Comment by amanuel2** [comment]
I told u this when u implemented. You just ignored lol . Hope u understand now
