### ISSUE TITLE
Help White Screen

### ISSUE THREAD

**Issue by MayhemBill** [Bone-Project/BoneOS#195]
BoneOS Version : V0.0.3

Describe Problem : Running today's release on Virtual Box, running the help command turns the whole screen white
 Link to Video: http://tinypic.com/r/hw0n4o/9

**Comment by amanuel2** [comment]
Wow this is a serious issue. We will work on solving this. If you have a stackoverflow and its >20reps you can chat with us in the chatroom here : http://chat.stackoverflow.com/rooms/125821/boneos

**Comment by MayhemBill** [comment]
Unfortunately I do not. I will tinker around see if I can find a solution for this though.

**Comment by amanuel2** [comment]
@TheHeroBilly or just join our slack at https://boneos.slack.com . Yeah im currently busy with school stuff ill be back on pumping up BoneOS in about 2-3 days... idk junior year is one heck of a year. @Fortunate-MAN

**Comment by double-fault** [comment]
This is an issue which has been rectified in one of the commits made after the release of v0.0.3. Please download the nightly builds in which this issue has been fixed. I'm going to update the iso file of v0.0.3 to fix this issue.

**Comment by double-fault** [comment]
The iso file of v0.0.3 has been updated, please download the file again and retry. If you still face the problem, post a comment here and I will look into this.

**Comment by double-fault** [comment]
Relevant discussion in StackOverflow chat: @srifqi [reported a similar bug in chat, and once I saw the bug he had reported](http://chat.stackoverflow.com/transcript/message/35493267#35493267), I immediately fixed it. So should be fixed now. Also, thanks for reporting the bug.
