### ISSUE TITLE
Uname and Date

### ISSUE THREAD

**Issue by amanuel2** [Bone-Project/BoneOS#196]
Uname and date are currently messud up. As well as watch --help which gives wrong info

**Comment by double-fault** [comment]
`uname` is messed up, ok, it was never working properly. What's wrong with `date`?

**Comment by double-fault** [comment]
Fixed the problem with watch command help.

**Comment by double-fault** [comment]
`date` works fine. Going to disable `uname` and `uptime` for now as they are broken.
