### ISSUE TITLE
Needs a goal

### ISSUE THREAD

**Issue by Gip-Gip** [Bone-Project/BoneOS#2]
What is the goal of BoneOS? How do you wish to accomplish it?

**Comment by amanuel2** [comment]
There are many goals within our slack team. We haven't published it yet. But I'm going to tell you it's interesting :)

**Comment by Gip-Gip** [comment]
@amanuel2 can you email the goals to me?

**Comment by amanuel2** [comment]
Yes but not all..  Everyone needs surprises.  And not the most creative ones just a preview ;)

**Comment by amanuel2** [comment]
@Gip-Gip Can we talk about this on a chat? Im not really an Email Person.

**Comment by Gip-Gip** [comment]
@amanuel2 yes, I just need to know how to access the chat

**Comment by amanuel2** [comment]
@Gip-Gip Here is a meeting i just setup for this issue : https://join.skype.com/O4xtEyoPVIIF  btw, dont get wiered out by my fast response , its because of slack bot notifying me in updates

**Comment by Gip-Gip** [comment]
@amanuel2 sorry I'm a bit late, my 9 year old laptop isn't handling Skype well.

**Comment by Gip-Gip** [comment]
@amanuel2 if you can, just refrain to email. Skype's being a pain on my computer and my phone

**Comment by amanuel2** [comment]
@Gip-Gip Ok :/

**Comment by amanuel2** [comment]
@Gip-Gip You can always go to [gitter](https://gitter.im/amanuel2/BoneOS) .. But if you say so. I have to go to sleep tonight. Comment me back on this issue by tommorow so i dont forget 😝

**Comment by Gip-Gip** [comment]
@amanuel2 Thank you for posting the gitter chat. I'll try to get it to work, but I have to sleep as well.
