### ISSUE TITLE
I know this project is mostly inactive, but if anyone is out there..

### ISSUE THREAD

**Issue by abclution** [Bone-Project/BoneOS#200]
I have an old embedded Askozia PBX (Alix embedded motherboard)  that the hardware for it is EOL.
Really want to continue running it and would like some assistance converting it to a virtual machine.

Have already managed to get it partially booted with Qemu (Proxmox) but it seems that the image init doesn't recognize any other storage other than "sd" storage and I don't really know if its possible to emulate the flash disk as an sd device.

I was considering trying to use BoneOS and grabbin all the Azkozia customizations on to it, but honestly I'm just looking for advice. Thanks

**Comment by amanuel2** [comment]
Hello are u still here? If u are be sure to reopen the issue!

**Comment by abclution** [comment]
OMG my github notifications need some work. I have no idea where they are going some days.

Hi yeah, I really want to rebuild the kernel for my Askoiza box so I can virtualize it, luckily they included the config but embedded systems is a bit beyond my experience.

A little research shows that Askozia was born from this project so I figured I would ask.
