### ISSUE TITLE
Fix slack badge

### ISSUE THREAD

**Issue by amanuel2** [Bone-Project/BoneOS#57]

**Comment by onlineth** [comment]
Working on it, trying to find a PHP based solution (if none exists, I'll go with [slackin](https://github.com/rauchg/slackin))

**Comment by onlineth** [comment]
I've got something setup on Heroku using slackin,
https://slack.boneos.org

![Badge](https://slack.boneos.org/badge.svg)

Going to test and make sure everything works over the next few days and then we should be all good.

**Comment by amanuel2** [comment]
Ok @onlineth, i think its good now.

**Comment by amanuel2** [comment]
[![Badge](https://slack.boneos.org/badge.svg)](https://slack.boneos.org) better version of badge that actually links to slack.boneos.org

**Comment by onlineth** [comment]
I agree @amanuel2, note that it's on Heroku on the free plan which means it ["sleeps" ever 30 minutes](https://devcenter.heroku.com/articles/free-dyno-hours#dyno-sleeping) without use. I haven't found this to be an issue; though, as it appears to have a pretty fast load all the time.
